name: ci-main
run-name: ci-main
on:
  workflow_dispatch:
  push:
#TU: Commented this out for testing so that pipeline will run on any branch
#    branches:
#    - main
  
jobs:
  anchore-scan:
    steps:
      - uses: ./.github/workflows/anchore-scan.yml
  tag-container-push:
    steps:
      - uses: ./.github/workflows/tag-container-push.yml
    needs: [anchore-scan]
